server:
  port: 80
  http:
    encoding:
      charset: utf8
    #文件上传限制
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  tomcat:
    uri-encoding: UTF-8

spring:
  resources:
    static-locations: classpath:/static/, classpath:/templates/

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    loginName: admin
    loginPassword: 123456
    druid:
      master:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=devdemodb
        username: sa
        password: nsoft
        initialSize: 1
        minIdle: 3
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
      slave:
        open: true
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=testdb
        username: sa
        password: nsoft
        initialSize: 1
        minIdle: 3
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: dev.base.entity
  config-location: classpath:config/mybatis-config.xml

#showSql
logging:
  config: classpath:config/logback.xml
  level:
    dev:
      base:
        mapper: debug